# Generated by Django 2.0.7 on 2018-07-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('EM ANDAMENTO', 'Em andamento'), ('FECHADO', 'Fechado'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=20),
        ),
    ]
