# Generated by Django 2.0.7 on 2018-07-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0002_indicacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
