# Generated by Django 2.0.7 on 2018-07-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0003_auto_20180707_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacao',
            name='created_by',
        ),
    ]
