# Generated by Django 2.1.3 on 2018-11-17 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicacaoPagamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pagamento', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('PAGO', 'Pago')], default='SOLICITADO', max_length=20)),
                ('valor_pagamento', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
            ],
        ),
        migrations.AlterModelOptions(
            name='indicacao',
            options={'verbose_name': 'Indicação', 'verbose_name_plural': 'indicações'},
        ),
        migrations.AddField(
            model_name='indicacaopagamentos',
            name='indicacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parceiros.Indicacao'),
        ),
    ]
