# Generated by Django 2.1.3 on 2018-11-17 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0005_auto_20181117_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicacaopagamentos',
            name='indicacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parceiros.Indicacao'),
        ),
    ]
