# Generated by Django 2.1.3 on 2018-11-17 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parceiros', '0006_auto_20181117_0309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicacaopagamentos',
            options={'verbose_name': 'pagamento', 'verbose_name_plural': 'pagamentos'},
        ),
        migrations.AddField(
            model_name='indicacaopagamentos',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicacaopagamentos',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='indicacaopagamentos',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
