# Generated by Django 2.0.7 on 2018-07-07 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parceiros', '0007_auto_20180707_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacao',
            name='user',
        ),
        migrations.AddField(
            model_name='indicacao',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
