# Generated by Django 2.0.7 on 2018-07-07 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0008_auto_20180707_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacao',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
