# Generated by Django 2.0.7 on 2018-07-07 22:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0010_indicacao_corretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='corretor',
            field=models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
