# Generated by Django 2.0.7 on 2018-07-07 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0011_auto_20180707_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicacao',
            name='corretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
