# Generated by Django 2.0.7 on 2018-07-08 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parceiros', '0013_auto_20180707_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacao_atualizacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
