# Generated by Django 2.0.7 on 2018-07-08 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0014_auto_20180708_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacao',
            name='last_modified_by',
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
